package commands

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"regexp"
	"time"

	"starbase/internal/model"
)

const (
	MaxSnippetBytes = 64 << 10
	MaxSnippetFiles = 8
)

var (
	SnippetIDRe   = regexp.MustCompile(`^[A-Za-z0-9]{8}$`)
	snippetFileRe = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,40}\.(js|html|css)$`)
)

// MaxSnippetStore caps all snippets together: anyone may save, and the
// disk may be shared with other services. (A variable for tests.)
var MaxSnippetStore int64 = 256 << 20

// ErrSnippetStoreFull means the snippets reached MaxSnippetStore.
var ErrSnippetStoreFull = errors.New("snippet storage is full")

// SaveSnippet stores playground code under a new, immutable id and shows
// the share link in the saving tab.
type SaveSnippet struct {
	SID, TabID string
	ID         string // generated by the handler
	Files      map[string]string
	Component  string // optional catalog slug
	UserID     int64  // 0 when anonymous
}

func (c SaveSnippet) Validate() error {
	if err := validTab(c.SID, c.TabID); err != nil {
		return err
	}
	if !SnippetIDRe.MatchString(c.ID) {
		return errors.New("bad snippet id")
	}
	if len(c.Files) == 0 || len(c.Files) > MaxSnippetFiles {
		return errors.New("a snippet has 1 to 8 files")
	}
	size := 0
	for name, body := range c.Files {
		if !snippetFileRe.MatchString(name) {
			return errors.New("bad file name " + name)
		}
		size += len(body)
	}
	if size > MaxSnippetBytes {
		return errors.New("snippet too large (max 64 KB)")
	}
	return nil
}

func (c SaveSnippet) Scope() string { return c.SID }

func (c SaveSnippet) Apply(ctx context.Context, tx *sql.Tx) error {
	files, err := json.Marshal(c.Files)
	if err != nil {
		return err
	}
	var comp, user any
	if c.Component != "" {
		comp = c.Component
	}
	if c.UserID != 0 {
		user = c.UserID
	}
	res, err := tx.ExecContext(ctx, `UPDATE snippet_stats SET bytes = bytes + ? WHERE id = 1 AND bytes + ? <= ?`,
		len(files), len(files), MaxSnippetStore)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrSnippetStoreFull
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO snippets (id, files, component, user_id, created_at) VALUES (?, ?, ?, ?, ?)`,
		c.ID, string(files), comp, user, time.Now().Unix()); err != nil {
		return err
	}
	return updateTab(ctx, tx, c.SID, c.TabID, model.TabState{}, func(st *model.TabState) {
		st.PlaygroundShare = c.ID
	})
}
