// Package tscheck type-checks playground code with the TypeScript compiler.
// The compiler is TypeScript's native port, a Go program that runs as a
// subprocess: `go run ./cmd/fetchtsc` downloads the pinned npm package for
// the build target into dist/, the binary embeds it, and the first check
// unpacks it next to the database. A binary built without it has no checker.
//
// types/ holds the declarations of the patched Datastar build, generated by
// `go tool task vendor` (scripts/vendor-rocket.sh) along with the bundle.
package tscheck

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha512"
	"encoding/base64"
	"fmt"
	"io"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strings"
)

// Version is the TypeScript release the binary embeds. A new one needs the
// integrity of each platform's package from the npm registry
// (https://registry.npmjs.org/@typescript/typescript-<platform>/<version>,
// dist.integrity); Dependabot doesn't see it.
const Version = "7.0.2"

var integrity = map[string]string{
	"linux-x64":    "sha512-EYdf2cNg7rgCWJnxCdJ+F3V39O8ihb37eHAu1LK8oAFizgTQbPOK7zHHXbPt8rX24COqODXeI3sIf0fCXG7H/A==",
	"linux-arm64":  "sha512-Qh4eU4/y3yDjnfjjyPYihMj5/ODIlmt+Bzu17OI+fiSRDW57QmU5SiN63exPRNJPKUzcc1INa1NXdrJ+MqHjUQ==",
	"darwin-x64":   "sha512-SZ9xZInqApNlNGc9s0W1VSsktYSOe9cFqNOIqmN1Gs8SmkjKZYFt017G4VwPxASInODuAdbTW7sXiFUf893RgA==",
	"darwin-arm64": "sha512-gowzar9MwS/aRWp6f3a4KUqzRjAZjOsmGNCM6LcTgXum+dBfgsBVMN+AgvOCCbguXyick6LJhpBszxMebJ8syA==",
	"win32-x64":    "sha512-0BQ3HkAHHlKLSp1qRvf3SUhGpGsDuhB/jgFw75guyqbxJqEaS0Cw/VFO8i2nHglJUzQCRtMMR/IBAKE3ETMC4g==",
}

// Platform is the npm platform of a Go target ("linux-x64"), or "" when
// TypeScript publishes no compiler for it.
func Platform(goos, goarch string) string {
	p := goos + "-" + map[string]string{"amd64": "x64", "arm64": "arm64"}[goarch]
	if goos == "windows" {
		p = "win32" + strings.TrimPrefix(p, goos)
	}
	if _, ok := integrity[p]; !ok {
		return ""
	}
	return p
}

// Tarball is the file name fetchtsc gives a platform's package in dist/.
func Tarball(platform string) string {
	return "typescript-" + platform + "-" + Version + ".tgz"
}

// Fetch downloads a platform's package from the npm registry and checks it
// against its pin.
func Fetch(ctx context.Context, platform string) ([]byte, error) {
	url := "https://registry.npmjs.org/@typescript/typescript-" + platform + "/-/typescript-" + platform + "-" + Version + ".tgz"
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", url, resp.Status)
	}
	tgz, err := io.ReadAll(io.LimitReader(resp.Body, 64<<20))
	if err != nil {
		return nil, err
	}
	return tgz, Verify(platform, tgz)
}

// Verify checks a package against the integrity npm publishes for it.
func Verify(platform string, tgz []byte) error {
	sum := sha512.Sum512(tgz)
	if got := "sha512-" + base64.StdEncoding.EncodeToString(sum[:]); got != integrity[platform] {
		return fmt.Errorf("typescript-%s %s: integrity %s, want %s", platform, Version, got, integrity[platform])
	}
	return nil
}

// Unpack writes the package's lib/ (the compiler and the lib.*.d.ts files it
// loads from its own folder) into dir.
func Unpack(tgz []byte, dir string) error {
	zr, err := gzip.NewReader(bytes.NewReader(tgz))
	if err != nil {
		return err
	}
	tr := tar.NewReader(zr)
	for {
		h, err := tr.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		name, ok := strings.CutPrefix(path.Clean(h.Name), "package/lib/")
		if !ok || h.Typeflag != tar.TypeReg || strings.Contains(name, "/") {
			continue
		}
		mode := os.FileMode(0o644)
		if name == "tsc" || name == "tsc.exe" {
			mode = 0o755
		}
		f, err := os.OpenFile(filepath.Join(dir, name), os.O_CREATE|os.O_WRONLY|os.O_TRUNC, mode)
		if err != nil {
			return err
		}
		_, err = io.Copy(f, tr)
		if cerr := f.Close(); err == nil {
			err = cerr
		}
		if err != nil {
			return err
		}
	}
}
