package catalog_test

import (
	"strings"
	"testing"
	"testing/fstest"

	"starbase/components"
	"starbase/internal/catalog"
)

// TestComponentsValid is the pull-request gate: every folder in components/
// must load, and must ship a manifest generated by the dev server.
func TestComponentsValid(t *testing.T) {
	cat, err := catalog.Load(components.FS)
	if err != nil {
		t.Fatalf("invalid components:\n%v", err)
	}
	if len(cat.Components) == 0 {
		t.Fatal("no components found")
	}
	for _, c := range cat.Components {
		if c.Manifest == nil {
			t.Errorf("%s: manifest.json missing: run `go tool task live` and open /components/%s", c.Slug, c.Slug)
			continue
		}
		if c.Manifest.Tag != c.Tag {
			t.Errorf("%s: manifest.json is for %q, want %q", c.Slug, c.Manifest.Tag, c.Tag)
		}
		if !strings.Contains(c.DocHTML, `class="demo"`) {
			t.Errorf("%s: README.md has no ```html preview example", c.Slug)
		}
	}
}

const validReadme = `---
name: Widget
tag: sb-widget
category: forms
summary: Does things.
author: octocat
since: 2026-09-21
preview: <sb-widget></sb-widget>
---
Hello.

## Examples

` + "```html preview\n<sb-widget></sb-widget>\n```\n"

func TestLoadValid(t *testing.T) {
	fsys := fstest.MapFS{
		"widget/README.md": {Data: []byte(validReadme)},
		"widget/widget.js": {Data: []byte("rocket('sb-widget', {})")},
	}
	cat, err := catalog.Load(fsys)
	if err != nil {
		t.Fatal(err)
	}
	c, ok := cat.Get("widget")
	if !ok {
		t.Fatal("widget not found")
	}
	if c.Name != "Widget" || c.Script != "widget/widget.js" || c.Hash == "" {
		t.Errorf("unexpected component: %+v", c.Meta)
	}
	if len(c.Headings) != 1 || c.Headings[0].ID != "examples" {
		t.Errorf("headings = %+v", c.Headings)
	}
	// Preview blocks render live and as source.
	if !strings.Contains(c.DocHTML, `<div class="demo-stage"><sb-widget></sb-widget>`) ||
		!strings.Contains(c.DocHTML, `class="chroma"`) {
		t.Errorf("preview block not rendered:\n%s", c.DocHTML)
	}
}

func TestLoadReportsEveryProblem(t *testing.T) {
	bad := strings.NewReplacer(
		"tag: sb-widget", "tag: widget",
		"category: forms", "category: spaceships",
		"since: 2026-09-21", "since: yesterday",
	).Replace(validReadme)
	fsys := fstest.MapFS{
		"widget/README.md":   {Data: []byte(bad)},
		"widget/widget.js":   {Data: []byte("rocket('sb-widget', {})")},
		"Bad_Name/README.md": {Data: []byte(validReadme)},
		"nojs/README.md":     {Data: []byte(validReadme)},
	}
	_, err := catalog.Load(fsys)
	if err == nil {
		t.Fatal("expected errors")
	}
	for _, want := range []string{"must look like sb-my-widget", "unknown category", "YYYY-MM-DD", "kebab-case", "missing nojs.js"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error does not mention %q:\n%v", want, err)
		}
	}
}

func TestDuplicateTags(t *testing.T) {
	fsys := fstest.MapFS{
		"a/README.md": {Data: []byte(validReadme)},
		"a/a.js":      {Data: []byte("rocket('sb-widget', {})")},
		"b/README.md": {Data: []byte(validReadme)},
		"b/b.js":      {Data: []byte("rocket('sb-widget', {})")},
	}
	if _, err := catalog.Load(fsys); err == nil || !strings.Contains(err.Error(), "already used") {
		t.Fatalf("err = %v", err)
	}
}
