#!/bin/sh
# Rebuilds components/code-editor/vendor/prism.js: Prism (core, markup, css,
# clike, javascript) + the js-templates plugin + Starbase extensions, wrapped
# as an ES module. Usage: PRISM_VERSION=1.30.0 sh scripts/vendor-prism.sh
set -eu
V="${PRISM_VERSION:-1.30.0}"
OUT=components/code-editor/vendor/prism.js
BASE="https://cdn.jsdelivr.net/npm/prismjs@$V"
{
	echo "// Prism $V (MIT, https://prismjs.com): core, markup, css, clike, javascript, js-templates."
	echo "// Vendored as an ES module for sb-code-editor; licence in LICENSE-prism.txt."
	echo "// Generated by scripts/vendor-prism.sh; do not edit by hand."
	# A /*! */ comment: minifiers keep it, so the shipped files carry the notice.
	echo "/*! Prism $V | MIT | https://prismjs.com */"
	echo "const previous = globalThis.Prism"
	echo "globalThis.Prism = { manual: true, disableWorkerMessageHandler: true }"
	# The language components, not the root prism.min.js: that one also bundles
	# the file-highlight plugin (which sb-code-editor never runs) and a source
	# map URL that doesn't exist here.
	for c in core markup css clike javascript js-templates; do
		curl -sSfL "$BASE/components/prism-$c.min.js"
		echo
	done
	cat <<'JS'
// Starbase extensions.
;(function (Prism) {
	// Rocket styles: const styles = /* css */ `…` (and /* html */ `…`).
	var tpl = /`(?:\\[\s\S]|\$\{(?:[^{}]|\{(?:[^{}]|\{[^}]*\})*\})+\}|(?!\$\{)[^\\`])*`/.source
	var commented = function (lang) {
		return {
			pattern: RegExp('(/\\*\\s*' + lang + '\\s*\\*/\\s*)' + tpl, 'i'),
			lookbehind: true,
			greedy: true,
			inside: {
				'template-punctuation': { pattern: /^`|`$/, alias: 'string' },
				'embedded-code': { pattern: /[\s\S]+/, alias: lang },
			},
		}
	}
	Prism.languages.javascript['template-string'].unshift(commented('css'), commented('html'))
	// Datastar: data-* attribute values are JavaScript expressions.
	Prism.languages.markup.tag.addAttribute('data-[\\w:.$-]+', 'javascript')
})(Prism)
JS
	echo "if (previous === undefined) delete globalThis.Prism"
	echo "else globalThis.Prism = previous"
	echo "export default Prism"
} > "$OUT"
curl -sSfL "https://raw.githubusercontent.com/PrismJS/prism/v$V/LICENSE" > components/code-editor/vendor/LICENSE-prism.txt
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
